/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: dwalsh (https://sketchfab.com/dwalsh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/energy-drink-game-ready-model-83676feb8b0a4589952cf3676299311b
Title: Energy Drink Game Ready Model
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import { ShaderMaterial } from '../../shaders/ShaderMaterial_4'

type GLTFResult = GLTF & {
  nodes: {
    LowRes_Can_Body_0: THREE.Mesh
    LowRes_Can_Alluminium_0: THREE.Mesh
  }
  materials: {
    Body: THREE.MeshStandardMaterial
    Alluminium: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const gltf = useGLTF('/model/energy_drink.glb') as unknown as GLTFResult
  const {materials,nodes} = gltf
    React.useEffect(()=>{
        materials.Body.roughness = 0.5
        materials.Body.metalness = 0.2
        materials.Alluminium.metalness = 1.0
        materials.Alluminium.roughness = 0.3
      return ()=>{
          gltf.scene.traverse(child=>{
              if ((child as THREE.Mesh).geometry) {
                  (child as THREE.Mesh).geometry.dispose()
              }
              if ((child as THREE.Mesh).material) {
                  const material =  (child as THREE.Mesh).material
                  if(Array.isArray(material)) material.forEach(m=>m.dispose)
                  else material.dispose()
              }
          })
        
      }
    },[gltf])
  return (
    <group {...props} dispose={null} scale={.1} position={[0,-0.5,0]} rotation={[0,Math.PI/2,0]}>
         {/* Main Lighting Setup */}
      <ambientLight intensity={0.5} />
      
      {/* Key light - main directional light */}
      <directionalLight
        position={[5, 5, 5]}
        intensity={1.5}
        castShadow
        shadow-mapSize-width={1024}
        shadow-mapSize-height={1024}
        shadow-camera-near={0.1}
        shadow-camera-far={50}
      />
      
      {/* Fill light - soft light from the opposite side */}
      <directionalLight
        position={[-5, 3, -5]}
        intensity={0.8}
        color="#fffeee"
      />
      
      {/* Rim/Back light - highlights edges */}
      <directionalLight
        position={[0, 5, -10]}
        intensity={1.2}
        color="#ffff00"
      />
      
      <group
        name="LowRes_Can"
        position={[0, 10.742, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={4.944}>
        <mesh
          name="LowRes_Can_Body_0"
          castShadow
          receiveShadow
          geometry={nodes.LowRes_Can_Body_0.geometry}
          material={materials.Body}
        >
            <ShaderMaterial material={materials.Body}/>
        </mesh>
        <mesh
          name="LowRes_Can_Alluminium_0"
          castShadow
          receiveShadow
          geometry={nodes.LowRes_Can_Alluminium_0.geometry}
          material={materials.Alluminium}
        >
            <ShaderMaterial material={materials.Alluminium}/>

        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/model/energy_drink.glb')
