/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: dark-minaz (https://sketchfab.com/dark-minaz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/monster-energy-drink-d9e8651b357e4b11909ae305024e1d37
Title: Monster Energy Drink
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import { ShaderMaterial } from '../../shaders/ShaderMaterial_1'

type GLTFResult = GLTF & {
    nodes: {
      Object_2: THREE.Mesh
    }
    materials: {
      initialShadingGroup: THREE.MeshStandardMaterial
    }
  }
  

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const gltf = useGLTF('/model/monster_energy.glb') as unknown as GLTFResult
  const {materials,nodes} = gltf
    React.useEffect(()=>{
      
      return ()=>{
          gltf.scene.traverse(child=>{
              if ((child as THREE.Mesh).geometry) {
                  (child as THREE.Mesh).geometry.dispose()
              }
              if ((child as THREE.Mesh).material) {
                  const material =  (child as THREE.Mesh).material
                  if(Array.isArray(material)) material.forEach(m=>m.dispose)
                  else material.dispose()
              }
          })
        
      }
    },[gltf])
  return (
    <group {...props} dispose={null} scale={.75} position={[0,-0.75,0]}>
         {/* Main Lighting Setup */}
         <ambientLight intensity={0.5} />
      
      {/* Key light - main directional light */}
      <directionalLight
        position={[5, 5, 5]}
        intensity={1.5}
        castShadow
        shadow-mapSize-width={1024}
        shadow-mapSize-height={1024}
        shadow-camera-near={0.1}
        shadow-camera-far={50}
      />
      
      {/* Fill light - soft light from the opposite side */}
      <directionalLight
        position={[-5, 3, -5]}
        intensity={0.8}
        color="#fffeee"
      />
      
      {/* Rim/Back light - highlights edges */}
      <directionalLight
        position={[0, 5, -10]}
        intensity={1.2}
        color="#ffff00"
      />
      <mesh
        name="Object_2"
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.initialShadingGroup}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <ShaderMaterial material={materials.initialShadingGroup}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/model/monster_energy.glb')
