/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: palladiumenergydrink (https://sketchfab.com/palladiumenergydrink)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/palladium-energy-drink-6cfa04ecb6694c138bdcb5bf105202fc
Title: Palladium Energy Drink
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import { ShaderMaterial } from '../../shaders/ShaderMaterial'

type GLTFResult = GLTF & {
  nodes: {
    Circle002_0: THREE.Mesh
    Sphere_0: THREE.Mesh
    Sphere001_0: THREE.Mesh
    Circle000_0: THREE.Mesh
    Circle001_0: THREE.Mesh
    Circle003_0: THREE.Mesh
    Circle_0: THREE.Mesh
    Circle004_0: THREE.Mesh
    Circle005_0: THREE.Mesh
    Sphere002_0: THREE.Mesh
    Circle006_0: THREE.Mesh
  }
  materials: {
    Aluminium: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
   const gltf = useGLTF('/model/palladium_energy_drink.glb') as unknown as GLTFResult
    const {materials,nodes} = gltf
      React.useEffect(()=>{
      
        return ()=>{
            gltf.scene.traverse(child=>{
                if ((child as THREE.Mesh).geometry) {
                    (child as THREE.Mesh).geometry.dispose()
                }
                if ((child as THREE.Mesh).material) {
                    const material =  (child as THREE.Mesh).material
                    if(Array.isArray(material)) material.forEach(m=>m.dispose)
                    else material.dispose()
                }
            })
          
        }
      },[gltf])
  return (
    <group {...props} dispose={null} scale={.175} position={[0,-0.7,0]} >
       {/* Main Lighting Setup */}
       <ambientLight intensity={0.5} />
      
      {/* Key light - main directional light */}
      <directionalLight
        position={[5, 5, 5]}
        intensity={1.5}
        castShadow
        shadow-mapSize-width={1024}
        shadow-mapSize-height={1024}
        shadow-camera-near={0.1}
        shadow-camera-far={50}
      />
      
      {/* Fill light - soft light from the opposite side */}
      <directionalLight
        position={[-5, 3, -5]}
        intensity={0.8}
        color="#fffeee"
      />
      
      {/* Rim/Back light - highlights edges */}
      <directionalLight
        position={[0, 5, -10]}
        intensity={1.2}
        color="#ffff00"
      />
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          name="Circle002_0"
          castShadow
          receiveShadow
          geometry={nodes.Circle002_0.geometry}
          material={materials.Aluminium}
          position={[0.085, 0.351, 14.387]}
        />
        <mesh
          name="Sphere_0"
          castShadow
          receiveShadow
          geometry={nodes.Sphere_0.geometry}
          material={materials['Material.001']}
          position={[0.082, 0.282, 11.706]}
          rotation={[0, 0, -1.205]}
        >
          <ShaderMaterial material={materials['Material.001']}/>
        </mesh>
        <mesh
          name="Sphere001_0"
          castShadow
          receiveShadow
          geometry={nodes.Sphere001_0.geometry}
          material={materials.Aluminium}
          position={[0.082, 0.282, 1.059]}
        >
          <ShaderMaterial material={materials.Aluminium}/>
        </mesh>
        <mesh
          name="Circle000_0"
          castShadow
          receiveShadow
          geometry={nodes.Circle000_0.geometry}
          material={materials.Aluminium}
          position={[0.086, -0.653, 14.436]}
        >
          <ShaderMaterial material={materials.Aluminium}/>
        </mesh>
        <mesh
          name="Circle001_0"
          castShadow
          receiveShadow
          geometry={nodes.Circle001_0.geometry}
          material={materials.Aluminium}
          position={[0.086, 1.204, 14.44]}
        >
          {/* <ShaderMaterial material={materials.Aluminium}/> */}
        </mesh>
        <mesh
          name="Circle003_0"
          castShadow
          receiveShadow
          geometry={nodes.Circle003_0.geometry}
          material={materials.Aluminium}
          position={[0.086, 0.305, 14.71]}
        />
        <mesh
          name="Circle_0"
          castShadow
          receiveShadow
          geometry={nodes.Circle_0.geometry}
          material={materials.Aluminium}
          position={[0.087, -0.169, 14.435]}
        />
        <mesh
          name="Circle004_0"
          castShadow
          receiveShadow
          geometry={nodes.Circle004_0.geometry}
          material={materials.Aluminium}
          position={[0.087, -0.134, 14.43]}
        />
        <mesh
          name="Circle005_0"
          castShadow
          receiveShadow
          geometry={nodes.Circle005_0.geometry}
          material={materials.Aluminium}
          position={[0.086, 0.394, 14.438]}
        >
          <ShaderMaterial material={materials.Aluminium}/>
        </mesh>
        <mesh
          name="Sphere002_0"
          castShadow
          receiveShadow
          geometry={nodes.Sphere002_0.geometry}
          material={materials.Aluminium}
          position={[0.082, 0.282, 0.419]}
        >
          {/* <ShaderMaterial material={materials.Aluminium}/> */}
        </mesh>
        <mesh
          name="Circle006_0"
          castShadow
          receiveShadow
          geometry={nodes.Circle006_0.geometry}
          material={materials.Aluminium}
          position={[0.091, 1.282, 14.371]}
        >
          {/* <ShaderMaterial material={materials.Aluminium}/> */}
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/model/palladium_energy_drink.glb')
