/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: funukemaguro (https://sketchfab.com/funukemaguro)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mega-crash-7days-to-die-2cd72f3214384234bf3a634cadb1818e
Title: Mega Crash 7Days To Die
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { ContactShadows, Environment, SoftShadows, useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body_Material001_0: THREE.Mesh
    Pull_Material001_0: THREE.Mesh
    Spout_Material001_0: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const gltf = useGLTF('/model/juice-can.glb') as unknown as GLTFResult
  const {nodes,materials,} = gltf

  React.useEffect(()=>{
    materials['Material.001'].envMapIntensity = 1
    materials['Material.001'].metalness = 0.05
    materials['Material.001'].roughness = 0.5
    return ()=>{
        gltf.scene.traverse(child=>{
            if ((child as THREE.Mesh).geometry) {
                (child as THREE.Mesh).geometry.dispose()
            }
            if ((child as THREE.Mesh).material) {
                const material =  (child as THREE.Mesh).material
                if(Array.isArray(material)) material.forEach(m=>m.dispose)
                else material.dispose()
            }
        })
    }
  },[gltf])
  return (
    <group {...props} scale={.275}>

<ambientLight intensity={.3} color="#ffffff" />
      
      {/* Main key light */}
      <directionalLight
        position={[10, 20, 10]}
        intensity={1}
        color="#ffeeee"
        castShadow
        shadow-mapSize={4096}
        shadow-normalBias={0.05}
      />
      
      {/* Fill light from opposite side */}
      <directionalLight
        position={[-10, 10, -10]}
        intensity={1.5}
        color="#eeeeff"
      />
      
      {/* Ground bounce light */}
      <directionalLight
        position={[0, -10, 0]}
        intensity={1}
        color="#ddddff"
      />
      
      {/* Overhead fill light */}
      <pointLight
        position={[0, 15, 0]}
        intensity={1}
        distance={20}
        decay={1}
        color="#ffffff"
      />
      
     
     
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Body_Material001_0.geometry}
            material={materials['Material.001']}
            position={[-0.02, 2.305, -0.009]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Pull_Material001_0.geometry}
            material={materials['Material.001']}
            position={[0.091, 4.914, 0.021]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Spout_Material001_0.geometry}
            material={materials['Material.001']}
            position={[0.11, 4.884, 0.007]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/juice-can.glb')
